### ISSUE TITLE
states broken in HA 0.18 and python-wink 0.7.4

### ISSUE THREAD

**Issue by captainnapalm** [python-wink/python-wink#35]
No longer receiving correct state for lights (and some other devices) when devices are toggled outside of HA. For example, if turn a light on/off from the switch, the state change isn't registered by HA, leaving it in the previous state until manipulated again by HA.

This is some of the errors from my logs.

```
16-04-20 23:07:12 homeassistant.core: BusHandler:Exception doing job
Traceback (most recent call last):
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\homeassistant\core.py", line 801, in job_handler
    func(arg)
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\homeassistant\helpers\event.py", line 176, in pattern_time_change_listener
    action(now)
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\homeassistant\helpers\entity_component.py", line 169, in _update_entity_states
    entity.update_ha_state(True)
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\homeassistant\helpers\entity.py", line 145, in update_ha_state
    self.update()
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\homeassistant\components\wink.py", line 102, in update
    self.wink.update_state()
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\pywink\devices\base.py", line 53, in update_state
    response = self.api_interface.get_device_state(self)
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\pywink\api.py", line 42, in get_device_state
    return arequest.json()
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
16-04-21 00:02:30 homeassistant.core: BusHandler:Exception doing job
Traceback (most recent call last):
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\homeassistant\core.py", line 801, in job_handler
    func(arg)
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\homeassistant\helpers\event.py", line 176, in pattern_time_change_listener
    action(now)
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\homeassistant\helpers\entity_component.py", line 169, in _update_entity_states
    entity.update_ha_state(True)
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\homeassistant\helpers\entity.py", line 145, in update_ha_state
    self.update()
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\homeassistant\components\lock\wink.py", line 52, in update
    self.wink.update_state()
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\pywink\devices\base.py", line 53, in update_state
    response = self.api_interface.get_device_state(self)
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\pywink\api.py", line 42, in get_device_state
    return arequest.json()
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
16-04-21 02:03:25 homeassistant.core: BusHandler:Exception doing job
Traceback (most recent call last):
  File "c:\users\brendan\appdata\local\programs\python\python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'
```

**Comment by bradsk88** [comment]
I've reproduced this problem on my end.  
Looking into it.

**Comment by bradsk88** [comment]
I was able to identify the problem and remedy it.  If this comes up again we can open a new issue.
